
services:
  web:
    container_name: mane-flask
    hostname: mane-flask
    build: ./app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports: 
      - '8000:5000'
    volumes:
      - ./app:/app
    networks:
      - default

volumes:
  persistent:
